#ifndef GAME_DEFS_H
#define GAME_DEFS_H

#define GAME_LAYER_GUI_FOREGROUND	0
#define GAME_LAYER_GUI_BACKGROUND	1
#define GAME_LAYER_LEVEL_FOREGROUND	2
#define GAME_LAYER_LEVEL_MID_1		3
#define GAME_LAYER_LEVEL_MID_2		4
#define GAME_LAYER_LEVEL_BACKGROUND	5
#define GAME_LAYER_BACKGROUND		6
#define GAME_LAYER_AMOUNT			7

#if SDL_BYTEORDER == SDL_BIG_ENDIAN

#define GAME_SURFACE_RMASK		0xff000000
#define GAME_SURFACE_GMASK 		0x00ff0000
#define GAME_SURFACE_BMASK 		0x0000ff00
#define GAME_SURFACE_AMASK 		0x000000ff

#else

#define GAME_SURFACE_RMASK		0x000000ff
#define GAME_SURFACE_GMASK		0x0000ff00
#define GAME_SURFACE_BMASK		0x00ff0000
#define GAME_SURFACE_AMASK		0xff000000

#endif

#endif
