.PHONY += libgame

INC_DIRS := libgame
LIBGAME_OBJS := game_control.o game_event.o game_global.o  game_module.o  game_object.o game_thread.o game_tools.o game_types.o

SUBDIRS := util

libgame: $(LIBGAME)
