.PHONY += libgame

INC_HEADERS := game_control.h game_defs.h game_event.h game_property.h game_thread.h game_tools.h game_types.h game.h
LIBGAME_OBJS := game_control.o game_event.o game_property.o game_thread.o game_tools.o game_types.o

SUBDIRS := object

libgame: $(LIBGAME)
